#单个键值对，冒号后面必须接空格！！！！！！！
me: 我自己
#缩进方式表示对象
server:
  port: 8081
#行列方式表示对象
user: {name: nihao,age: 18}
#配置数组(List,Set)数据
city:
  - 天津
  - 北京
  - 上海
#或者
city1: [天津,北京,上海]
#集合中的元素是对象形式
student:
  - name: 我自己
    age: 18
    sex: 男
  - name: niaho
    age: 17
    sex: 女
#map集合
map:
  key1: value1
  key2: value2